name: aTopPlayers
main: AlexBrin\aTopPlayers
version: 1.0.1
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
author: BlawoHD

commands:
  atp:
    default: op
    description: Top-Spieler
    permission: atp.use
permissions:
  atp:
    default: op
    chidlren:
      atp.use:
        default: op
